import { Metadata } from 'next'
import React from 'react'
import LessonHeader from './_components/LessonHeader'
import LessonNavigation from './_components/LessonNavigation'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<>
			<div className="flex flex-col min-h-screen">
				<LessonHeader />
				<div className="flex-grow h-full">{children}</div>
				<LessonNavigation />
			</div>
		</>
	)
}
