import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
	title: 'Fraktale',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return <>{children}</>
}
